### ISSUE TITLE
Text adjust

### ISSUE THREAD

**Issue by josielrocha** [ireade/Toast.js#3]
Hi, just a litle thing...

Here [https://github.com/ireade/Toast.js/blob/master/dist/js/Toast-ES6.js#L4] there is text error:
throw new Error('Toast.js - You need to set a `mesasge` to display');

Happy coding!

**Comment by ireade** [comment]
Hi @josielrocha I don't see what the issue is, what's the problem?

**Comment by 0lumide** [comment]
I think he was saying there's a typo. You wrote "mesasge" instead of "message"

**Comment by ireade** [comment]
Ah okay, I read it so many times and didn't see the error! Thanks @0lumide
