### ISSUE TITLE
Auto-dismiss

### ISSUE THREAD

**Issue by georgeharnwell** [ireade/Toast.js#7]
Would be great if the toasts could be set to dismiss themselves after n number of milliseconds. I can see it becoming quite tedious having to manually dismiss every alert.

**Comment by gremdev** [comment]
@georgeharnwell You can try this https://gist.github.com/gremdev/07adc5094d0a2a861491d24e38aac0b0 . I added auto-dismiss, duration feature.

**Comment by georgeharnwell** [comment]
I'll give this a go later on. Is that new? It's exactly what I need so I'll be really grateful if it works!

**Comment by gremdev** [comment]
It's the same library but I tweaked it a little bit to have auto-dismiss feature.

**Comment by georgeharnwell** [comment]
Works like a charm. Fantastic
